### ISSUE TITLE
Configure RuboCop Along with CodeFactor

### ISSUE THREAD

**Issue by marcfreiheit** [hpi-swt2/vm-portal#119]
**Description**
As a Developer
I would like to have RuboCop configured with all tools it ship with
In order to reduce time wasted on fixing unnecessary style guidelines and automate linting of my source code.

**Acceptance Criteria:**
- [ ] I can run `rubocop` without major doubt breaking the whole source code
- [ ] I can check CodeFactor to validate my software quality
- [ ] CodeFactor doesn't block my Pull Requests for minor quality issues

**Priority**
Medium

**Pain Points**
2

**Comment by chrisma** [comment]
As far as I can see, the project is configured to only require Travis CI to pass in order to allow merging:

![image](https://user-images.githubusercontent.com/1652117/49579547-d5869d80-f94c-11e8-89de-8b1abf5a9fd0.png)

All other services are optional.
These settings can be altered in the GitHub settings of this repository for the dev branch [here](https://github.com/hpi-swt2/vm-portal/settings/branch_protection_rules/2846878) as well as for the master branch [here](https://github.com/hpi-swt2/vm-portal/settings/branch_protection_rules/2823552)

**Comment by chrisma** [comment]
The project's [README file](https://github.com/hpi-swt2/vm-portal#linting) contains some information as well as links for configuring Rubocop

**Comment by skydivin4ng3l** [comment]
who is responsible for decisions concerning the linting? How can we check if the current configuration is what "we" need and want? Does codefactor, Codebeat and rubocop need to be aligned manually?

**Comment by Kenneth-Schroeder** [comment]
New goal: remove Codebeat (@skydivin4ng3l) and ignore codefactor-info-notifications if possible. (@MkuuWaUjinga )

**Comment by MkuuWaUjinga** [comment]
Unfortunately, I haven't found a way to ignore minor issues (codefactor-info-notification) for green builds. It seems that the severity of issues is determined by following metrics: issue code size, files change frequency and file size, so just picking minor issues and ignore them is not a good idea, because they might become major issues...

**Comment by skydivin4ng3l** [comment]
I discussed the fact, for local Rubocop with my team, the code base is not rubocoped as we already discussed. But if someone tries to fix alle the code base then everybody will get merge conflicts cause of the multitude of changes. 

So it would be best if we all have a phase where everybody would merge their important current changes into dev.

- No one branches from dev like a freeze
- Someone makes a commit with all the rubocop fixes. 
- Unfreeze

Without this phase we may have a lot of conflicts to solve.
