### ISSUE TITLE
Warning Pop-Ups

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#178]
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As a user
I want to have a warning pop up when I am about to do something irreversible or potentially dangerous
in order to not accidentally click "delete" on something important.

**Acceptance Criteria:**

- [ ] A Template for Warnings exists and is made available to all teams to implement when needed.
- [ ] Warning Popups show up on the following occasions:
- When hitting the "Shut Down" and "Reset" buttons on a VM
- When archiving a VM
- Remove warning on /notifications page.

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

**Comment by hkohlsaat** [comment]
Template for warnings would be over-engineering since the only thing that is required to warn about a critical action is appending `data: { confirm: 'Are you sure?' }` to the `link_to` or `button_to` helper calls.

Securing "Archive" on VM cannot be done since there aren't any "Archive" buttons, as far as I can see.
