### ISSUE TITLE
Strong parameters for VM Controller

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#21]
The parameters of the VM controller should be validated using the idea of "strong parameters":
https://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html

**Comment by Askir** [comment]
`This makes Action Controller parameters forbidden to be used in Active Model mass assignment until they have been explicitly enumerated.` What exactly is the use if we don't have an Active model behind everything?

I would usually have used them but since Vms are only represented in VSphere right now I don't think it does anything and just adds an unnecessary layer. @chrisma

**Comment by chrisma** [comment]
Ok, makes sense!
Would you please add this reasoning as a comment to the VM Controller file?

**Comment by Askir** [comment]
yes will do!
