### ISSUE TITLE
user management for servers

### ISSUE THREAD

**Issue by krichly** [hpi-swt2/vm-portal#401]
**User Story**

Copy the user management functionality from the vms page and integrate it on the server pages.  

**Acceptance Criteria:**

- [ ] I can manage the users on servers

**Comment by BraunTom** [comment]
With puppet script

**Comment by krichly** [comment]
yes

**Comment by chrisma** [comment]
Please investigate where code could be deduplicated here.

**Comment by MrModder** [comment]
Having looked at the way the puppet scripts and git are currently implemented, I would advise to split this issue into 3 different ones:
1. Refactor the users and sudo_users to conform to rails standards
    * Currently, users and sudo_users don't behave like attributes of models, as they are saved immediately, not after validation and must always be assigned separately, instead of simply being assigned during update
2. Refactor the PuppetScripts and GitHelper modules
    * These modules could both be abstracted into much higher-level functions, which would reduce code-duplication a lot (@chrisma) and make the entire module much easier to mock.
3. User management for servers
    * Please be more specific about the acceptance criteria here
      * How should the puppet scripts be formatted exactly? what classes are needed here? What files?

**Comment by chrisma** [comment]
> User management for servers
> 
>     * Please be more specific about the acceptance criteria here
>       
>       * How should the puppet scripts be formatted exactly? what classes are needed here? What files?

@mat156

**Comment by chrisma** [comment]
@MrModder Thanks for investigating!

Would you open issues with the required work items for your first two ideas?
We'll keep this issue to discuss implementation details of user management for servers

**Comment by mat156** [comment]
> * How should the puppet scripts be formatted exactly? what classes are needed here? What files?

server should be treated exactly like VM's. node and name file should be formatted the same way.

**Comment by chrisma** [comment]
VMs have name format `"#{Time.now.strftime('%Y%m%d')}_vm-#{name}"`.

**Comment by MrModder** [comment]
> VMs have name format "#{Time.now.strftime('%Y%m%d')}_vm-#{name}".

This may actually be true in vSphere but as in #425 described, we only changed the name for the VMs in vSphere.
Do we need to update the name in the puppet scripts as well?
If not, how should we then differentiate scripts for servers from scripts for admins?

**Comment by chrisma** [comment]
@MrModder Thanks for looking into this.

> Do we need to update the name in the puppet scripts as well?

I would think so. @mat156 ?

> If not, how should we then differentiate scripts for servers from scripts for admins?

Do you mean "differentiate scripts for servers from scripts for *VMs*"? If so, I would suggest changeing the `vm` part of the naming scheme to `server`, i.e. `"#{Time.now.strftime('%Y%m%d')}_server-#{name}"`

**Comment by MrModder** [comment]
> Do you mean "differentiate scripts for servers from scripts for VMs"? If so, I would suggest changing the vm part of the naming scheme to server, i.e. "#{Time.now.strftime('%Y%m%d')}_server-#{name}"

Oh, yes of course, scripts for VMs, not admins 😅

We will definitely need more information on the exact contents of the puppet scripts, both for the Virtual Machines and the Servers. (@mat156 )
* Do they need to have the full vm name, including prefix (this might be a rather large refactoring)?
* How are the puppet scripts for servers different than the puppet scripts for VMs?
    * If they are not, we could ensure that no servers/VMs can overlap in naming
* Should they be in the same folders in the git repository?
* Do servers also need a prefix? What should that look like? I don't think prefix with timestamp would make much sense as we don't create the servers, meaning we can't control the actual naming of the servers, we just reflect them in HART.
* I have now added validation for the naming of servers similar to the one for VMs, is this intended?
If not, how should we make sure that the naming of servers is compatible with the required syntax for puppet scripts?

If you can, please show us some examples on how puppet scripts both for VMs and servers should look like, I think this would explain a lot.

Note: I'm also waiting for #521 to be merged, because it includes major refactorings in the servers controller.

**Comment by BjoernDaase** [comment]
@MrModder I did the merge just now. Please have a look if everything is fine and merge it if so.

**Comment by mat156** [comment]
servers neither have a timestamp nor any prefix. they are created as is and the admin has to take care of name collisions.
for the puppet scripts: servers have to reside in the same folders, they have exactly the same content as VM's.

**Comment by MrModder** [comment]
Ok, so now we know how the puppet scripts for servers should look like.

> Do they need to have the full vm name, including prefix (this might be a rather large refactoring)?

But we still need to know what the VM scripts should look like exactly?
Do they now need their prefix somewhere in the puppet scripts?
Or do they not?

> I have now added validation for the naming of servers similar to the one for VMs, is this intended?
If not, how should we make sure that the naming of servers is compatible with the required syntax for puppet scripts?

What about this?
@mat156
