### ISSUE TITLE
Handle errors when reading node files

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#455]
`/var/www/vm-swt-hrmt-master.eaalab.hpi.uni-potsdam.de/current$ tail -f -n 200 log/production.log`:

```
I, [2019-03-08T09:24:02.434405 #4965]  INFO -- : [8b37055c-36a0-4d09-bc03-5e174672c6f9] Completed 500 Internal Server Error in 1041ms (ActiveRecord: 33.1ms)
F, [2019-03-08T09:24:02.442079 #4965] FATAL -- : [8b37055c-36a0-4d09-bc03-5e174672c6f9]   
F, [2019-03-08T09:24:02.449264 #4965] FATAL -- : [8b37055c-36a0-4d09-bc03-5e174672c6f9] RuntimeError (Unsupported Format):
F, [2019-03-08T09:24:02.449516 #4965] FATAL -- : [8b37055c-36a0-4d09-bc03-5e174672c6f9]   
F, [2019-03-08T09:24:02.449722 #4965] FATAL -- : [8b37055c-36a0-4d09-bc03-5e174672c6f9] lib/puppetscript.rb:91:in `read_node_file'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/api/v_sphere/virtual_machine.rb:71:in `includes_user?'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/api/v_sphere/virtual_machine.rb:82:in `block (2 levels) in user_vms'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/api/v_sphere/virtual_machine.rb:81:in `each'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/api/v_sphere/virtual_machine.rb:81:in `block in user_vms'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] lib/git_helper.rb:9:in `open_repository'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/api/v_sphere/virtual_machine.rb:79:in `user_vms'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/controllers/dashboard_controller.rb:27:in `filter_vm_categories'
[8b37055c-36a0-4d09-bc03-5e174672c6f9] app/controllers/dashboard_controller.rb:14:in `index'
```

This behavior is caused by the exception raised in `lib/puppetscript.rb`:
`raise 'Unsupported Format' unless node_file_correct?(vm_name, contents)`
The exception is never handled, leading to a 500 error response, making the entire system unusable.

Instead of failing, we should:
* Investigate why `lib/puppetscript.rb` code is run when rendering the dashboard
* Provide a better error message than 'Unsupported format', mentioning a problem with the affected file.
* Communicate the issue with the file to the user, possibly with a link to the repo path.
* Enable usage of the rest of the system, even while some puppetfiles do not validate

**Comment by chrisma** [comment]
Looking at `spec/lib/puppetscript_spec.rb`, the most likely offender is:

`raises an error if trying to read a puppet file with the node name not matching the file name`

Is the generation of file names and node names correct? Are there tests for this?
Currently, the repository contains file names such as `node-vm-pxetest-hartdev.pp` which contain classes such as `class node_vm-pxetest-hartdev`, i.e. not all dashes were replaced.

**Comment by BjoernDaase** [comment]
@chrisma We are aware of this issue and will fix this.  
Let me give you an answer on your first question 

> Investigate why lib/puppetscript.rb code is run when rendering the dashboard

On the dashboard we show the same VMs as on the VMs details page. So we have to check whether a user, who is not an admin, may see a VM. Therefore we have to go through all VMs, get their puppetscript, extract users and admins out of it, and then compare the result to the current user. Only if we have a match here, we show the VM to the user. That's the reason why the `lib/puppetscript.rb` code is run there.  
If the current user is an admin, we obviously can skip all these checks, so they still see the dashboard.  

> Provide a better error message than 'Unsupported format', mentioning a problem with the affected file.

We should not show the VM at all because the current user may not be allowed to know about the existence of this VM. But yes, you are right, we obviously have to handle invalid files way better.  

> Communicate the issue with the file to the user, possibly with a link to the repo path.

We could do this on the VM details page (where we have the same problem --> Error 500) if the file is not correct (maybe in this section, where we show a list of all users, if the file is correct). But we could only do this for admins, because we can't know whether another user may know about the existence of the VM. 

> Enable usage of the rest of the system, even while some puppetfiles do not validate

Sure!

> Is the generation of file names and node names correct? Are there tests for this?

Yes and yes. The problem is the following: We had https://github.com/hpi-swt2/vm-portal/pull/441 which changes a '-' in the VM name to a '_' in the puppetscript. When now reading the puppetscripts we obviously have to expect underscores and no dashes as well. The puppetscripts, which produce problems are now those, which where generated before https://github.com/hpi-swt2/vm-portal/pull/441  and have at least one dash in the VM name. The problem does not occur with never VMs.

> Currently, the repository contains file names such as node-vm-pxetest-hartdev.pp which contain classes such as class node_vm-pxetest-hartdev, i.e. not all dashes were replaced and file name and class name do not match.

That's correct and intended behavior. See https://github.com/hpi-swt2/vm-portal/issues/423 or ask @mat156 for details.
