### ISSUE TITLE
Constants in api/v_sphere/folder.rb

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/vm-portal#487]
`app/api/v_sphere/folder.rb` contains some constants regarding network config. Should these be configurable in the `AppSettings`?

![image](https://user-images.githubusercontent.com/1652117/54535567-113ef380-498f-11e9-8891-c18c52acc437.png)

**Comment by chrisma** [comment]
@mat156 ?

**Comment by mat156** [comment]
please move deviceName 'VM Network' to settings, make it configurable

**Comment by BjoernDaase** [comment]
@chrisma This issue is contradictory with #449, in which @mat156 requested that the first network returned by the vSphere API (`clsuter.network`) is selected as the network (`deviceName`).  
This being already merged into `dev` the code snippet looks as follows currently:
![Screenshot from 2019-03-23 17-43-32](https://user-images.githubusercontent.com/24682367/54869021-35d20b80-4d93-11e9-8684-a857e0b85df7.png)

**Comment by chrisma** [comment]
Thanks for the heads up! this is resolved then,
